#!/bin/sh
#
#    __________  _____  __       _  __________ __  ____ 
#   / ____/ __ \/   \ \/ /      | |/ / ____/ // / / __ \
#  / /   / /_/ / /| |\  /       |   / /   / // /_/ / / /
# / /___/ _, _/ ___ |/ /       /   / /___/__  __/ /_/ / 
# \____/_/ |_/_/  |_/_/       /_/|_\____/  /_/  \____/  
#                                                      
#
#
# Build script to build hdf5 on CRAY XC40
#
# Usage: build_hdf5

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

USAGE()
{
cat <<EOF

Makes HDF5 library for CRAY XC40.
==================================

build_hdf5 builds the HDF5 library by running configure, make and make install.
It skips the configure part if one has been done already.  In effect, one
can continue from a previous build.

Command Syntax
==============
$0 [-compiler <OPT>] [-help] [-srcdir dir] HDF5 config-arguments ...

   -compiler    options are: intel [D], cray, gnu
   -help:	show this help page
   -srcdir:	directory with the HDF5 source resides

all other arguments are passed to HDF5 configure command

EXAMPLE:
  ../build_hdf5/CRAY_XC40/build_hdf5 -srcdir \$PWD../ --prefix=\$PWD/build --enable-fortran --enable-shared --enable-parallel

EOF
}
CONFIG_ONLY=no
BUILD_AUTOTOOLS_DIR=""
SRCDIR="."
INSTALLDIR=""
CONFIGURE="./configure"
COMPILER_ID=""
# Main
# Parse command options
while [ $# -gt 0 ]; do
    case "$1" in
	-help)
	    USAGE
	    exit 0
	    ;;
	--help)
	    USAGE
	    exit 0
	    ;;
        -build_autotools)
	    shift
	    BUILD_AUTOTOOLS_DIR="$1"
	    ;;
	-srcdir)
	    shift
	    SRCDIR="$1"
	    ;;
        -compiler)
	    shift
	    COMPILER_ID="$1"
	    ;;

	*)	# pass it as a configure option
	    CONFIG_OP="$CONFIG_OP $1"
	    ;;
    esac
    shift
done

if ! [ $BUILD_AUTOTOOLS_DIR == ""];then
    if [ -f $BUILD_AUTOTOOLS_DIR/preinstall_hdf5.sh ]; then
	$BUILD_AUTOTOOLS_DIR/preinstall_hdf5.sh
	if [ $? -ne 0 ]; then
	    echo "preinstall_hdf5.sh FAILED"
	    exit 1
	fi
	export PATH=$BUILD_AUTOTOOLS_DIR/util/bin:$PATH
    else
	printf "${RED} ERROR: can't find preinstall_hdf5.sh in $BUILD_AUTOTOOLS_DIR.  Aborted.${NC}\n"
	exit 1
    fi
fi

if [ -d $SRCDIR ]; then
   CONFIGURE="$SRCDIR/configure"
else
   printf "${RED}ERROR: can't find HDF5 source in $SRCDIR.  Aborted. ${NC}\n"
   exit 1
fi

# if 'configure' does not exists then generate it
if ! [ -f $CONFIGURE ]; then
  $SRCDIR/autogen.sh
fi

export CC="cc"
export FC="ftn"
export CXX="CC"
export CFLAGS="-fPIC"
export FCFLAGS="-fPIC"
export LDFLAGS="-dynamic"

if [[ ("$COMPILER_ID" == "intel") || ("$COMPILER_ID" == "")]]; then
  export CFLAGS="-Ofast"
  export FCFLAGS="-Ofast"
fi

CONFIGURE="$CONFIGURE $CONFIG_OP"

printf "${YELLOW} $CONFIGURE ${NC}\n"
$CONFIGURE
if [ $? -ne 0 ]; then
    printf "${RED}error in Configure.  Aborted.${NC}\n"
    exit 1
fi
make -j8
if [ $? -ne 0 ]; then
    printf "{RED}error in make.  Aborted.${NC}\n"
    exit 1
fi
make install
if [ $? -ne 0 ]; then
    printf "{RED}error in make install.  Aborted.${NC}\n"
    exit 1
fi

